using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using System.Diagnostics;
using System.Text;
using System.Threading;

// Retry tool: reads the CSV produced by ToolDownCollectionNexusMod and re-runs the
// download flow (Phase 2) ONLY for mods whose status is not "done".
class Program
{
    // ====== CONFIG ======
    // The progress CSV generated by the main tool (Index,Name,Url,Status,UpdatedAt).
    // It is read at start and rewritten in place as failed mods are retried.
    const string CsvPath = @"D:\1\Tool\ToolDownCollectionNexusMod\collection_progress.csv";

    // Folder that contains msedgedriver.exe (reuse the main project's driver)
    const string DriverPath = @"D:\1\Tool\ToolDownCollectionNexusMod\driver";

    // Same Edge profile used by the main tool (keeps the NexusMods login / Cloudflare clearance)
    const string UserDataDir = @"D:\Temp";
    const string ProfileDirectory = "Profile 1";

    // A mod is considered successful (skip on retry) when its status is one of these
    static readonly string[] SuccessStatuses = { "done" };

    static void Main()
    {
        if (!File.Exists(CsvPath))
        {
            Console.WriteLine("CSV not found: " + CsvPath);
            return;
        }

        // Load every row; keep them all so the rewritten CSV stays complete
        var mods = LoadCsv(CsvPath);
        Console.WriteLine($"Loaded {mods.Count} rows from {CsvPath}");

        // Retry only the mods that are NOT successful and have a URL
        var toRetry = mods
            .Where(m => !IsSuccess(m.Status) && !string.IsNullOrWhiteSpace(m.Url))
            .ToList();

        Console.WriteLine($"{toRetry.Count} mod(s) to retry (status != done).");
        if (toRetry.Count == 0)
        {
            Console.WriteLine("Nothing to retry. Done.");
            return;
        }

        // Edge must be fully closed for Selenium to use the profile
        KillEdgeProcesses();

        var options = new EdgeOptions();
        options.AddArgument("--start-maximized");
        options.AddArgument($"user-data-dir={UserDataDir}");
        options.AddArgument($"profile-directory={ProfileDirectory}");
        options.AddArgument("--disable-blink-features=AutomationControlled");
        options.AddExcludedArgument("enable-automation");
        options.AddAdditionalEdgeOption("useAutomationExtension", false);

        var service = EdgeDriverService.CreateDefaultService(DriverPath);
        var driver = new EdgeDriver(service, options);

        try
        {
            driver.ExecuteCdpCommand("Page.addScriptToEvaluateOnNewDocument",
                new Dictionary<string, object>
                {
                    ["source"] = "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
                });
        }
        catch (Exception ex)
        {
            Console.WriteLine("Could not set CDP override (skipping): " + ex.Message);
        }

        // Let the user handle any Cloudflare check / login before we start
        driver.Navigate().GoToUrl("https://www.nexusmods.com/");
        Console.WriteLine("If there is still a Cloudflare check or you are not logged in: handle it in the browser, then press ENTER to continue...");
        Console.ReadLine();

        string mainTab = driver.WindowHandles.First();

        int n = 0;
        foreach (var mod in toRetry)
        {
            n++;
            string filesUrl = mod.Url.Contains("?") ? mod.Url + "&tab=files" : mod.Url + "?tab=files";
            Console.WriteLine($"[{n}/{toRetry.Count}] (row {mod.Index}) {mod.Name} -> {filesUrl}");

            try
            {
                // Open the mod's Files tab in a NEW browser tab and switch to it
                ((IJavaScriptExecutor)driver).ExecuteScript("window.open(arguments[0], '_blank');", filesUrl);
                Thread.Sleep(1000);
                driver.SwitchTo().Window(driver.WindowHandles.Last());
                Thread.Sleep(4000);
                SetStatus(mods, mod, "opened");

                // The download UI lives inside a Web Component (<mod-download-modal>) Shadow DOM,
                // so we click via JS that pierces shadow roots (DeepClick).

                // 1) Click the "Manual" button -> the download popup opens
                bool manualClicked = false;
                WaitFor(() => { manualClicked = DeepClick(driver, "button", "Manual"); return manualClicked; }, 8000);
                if (!manualClicked)
                {
                    Console.WriteLine("  'Manual' button not found -> skip.");
                    SetStatus(mods, mod, "manual-not-found");
                }
                else
                {
                    SetStatus(mods, mod, "manual-clicked");

                    // 2) In the popup: click the "Manual download" link (href .../api/files/<id>/download)
                    bool manualDlClicked = false;
                    WaitFor(() => { manualDlClicked = DeepClick(driver, "a[href*='/api/files/']", ""); return manualDlClicked; }, 6000);
                    if (manualDlClicked)
                    {
                        SetStatus(mods, mod, "manualdl-clicked");
                    }
                    else
                    {
                        Console.WriteLine("  'Manual download' link not found.");
                        SetStatus(mods, mod, "manualdl-not-found");
                    }

                    // 3) Click the "Slow download" button (free tier)
                    bool slowClicked = false;
                    WaitFor(() => { slowClicked = DeepClick(driver, "button", "Slow download"); return slowClicked; }, 8000);
                    if (slowClicked)
                    {
                        SetStatus(mods, mod, "slow-clicked");
                    }
                    else
                    {
                        Console.WriteLine("  'Slow download' button not found (maybe Premium / already downloading).");
                        SetStatus(mods, mod, "slow-not-found");
                    }
                }

                // Wait ~6s for the download to start
                Thread.Sleep(6000);

                if (mod.Status == "slow-clicked" || mod.Status == "manualdl-clicked")
                    SetStatus(mods, mod, "done");
            }
            catch (WebDriverException ex)
            {
                Console.WriteLine("  Error while processing mod: " + ex.Message);
                SetStatus(mods, mod, "error: " + ex.Message.Replace("\r", " ").Replace("\n", " "));
            }
            finally
            {
                try
                {
                    if (driver.WindowHandles.Count > 1)
                    {
                        driver.Close();
                        driver.SwitchTo().Window(mainTab);
                    }
                }
                catch (WebDriverException) { }
            }
        }

        driver.Quit();
        SaveProgress(mods);
        int remaining = mods.Count(m => !IsSuccess(m.Status));
        Console.WriteLine($"Done! {mods.Count - remaining}/{mods.Count} mods now successful. CSV: {CsvPath}");
    }

    static bool IsSuccess(string status)
    {
        return SuccessStatuses.Contains((status ?? "").Trim().ToLowerInvariant());
    }

    // Kill any running Edge/driver processes to release the profile lock
    static void KillEdgeProcesses()
    {
        foreach (var name in new[] { "msedge", "msedgedriver" })
        {
            foreach (var p in Process.GetProcessesByName(name))
            {
                try { p.Kill(true); p.WaitForExit(3000); }
                catch { /* already exited / cannot kill -> ignore */ }
            }
        }
        Thread.Sleep(1000);
    }

    // JS: search light DOM + every shadow root for the first element matching `selector`
    // (and, if `text` is non-empty, whose trimmed text equals it), then click it.
    const string DeepClickJs = @"
const selector = arguments[0];
const text = (arguments[1] || '').trim().toLowerCase();
function search(root){
  let nodes = [];
  try { nodes = root.querySelectorAll(selector); } catch (e) {}
  for (const el of nodes){
    if (text === '' || (el.textContent || '').trim().toLowerCase() === text){
      el.click();
      return true;
    }
  }
  const all = root.querySelectorAll('*');
  for (const el of all){
    if (el.shadowRoot && search(el.shadowRoot)) return true;
  }
  return false;
}
return search(document);
";

    static bool DeepClick(EdgeDriver driver, string selector, string text)
    {
        try
        {
            var r = ((IJavaScriptExecutor)driver).ExecuteScript(DeepClickJs, selector, text ?? "");
            return r is bool b && b;
        }
        catch (WebDriverException)
        {
            return false;
        }
    }

    static bool WaitFor(Func<bool> cond, int timeoutMs, int stepMs = 300)
    {
        int waited = 0;
        while (waited < timeoutMs)
        {
            try { if (cond()) return true; }
            catch (WebDriverException) { }
            Thread.Sleep(stepMs);
            waited += stepMs;
        }
        return false;
    }

    // Update one mod's status + timestamp, log it, and rewrite the CSV
    static void SetStatus(List<ModEntry> mods, ModEntry mod, string status)
    {
        mod.Status = status;
        mod.UpdatedAt = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
        Console.WriteLine($"    -> {status}");
        SaveProgress(mods);
    }

    // ====== CSV read/write ======
    static List<ModEntry> LoadCsv(string path)
    {
        var list = new List<ModEntry>();
        var lines = File.ReadAllLines(path);
        for (int i = 1; i < lines.Length; i++) // skip header row
        {
            if (string.IsNullOrWhiteSpace(lines[i])) continue;
            var f = ParseCsvLine(lines[i]);
            if (f.Count < 4) continue;
            list.Add(new ModEntry
            {
                Index = int.TryParse(f[0], out var idx) ? idx : list.Count + 1,
                Name = f[1],
                Url = f[2],
                Status = f[3],
                UpdatedAt = f.Count > 4 ? f[4] : ""
            });
        }
        return list;
    }

    // Parse one CSV line into fields (handles quoted fields with commas / doubled quotes)
    static List<string> ParseCsvLine(string line)
    {
        var fields = new List<string>();
        var sb = new StringBuilder();
        bool inQuotes = false;
        for (int i = 0; i < line.Length; i++)
        {
            char c = line[i];
            if (inQuotes)
            {
                if (c == '"')
                {
                    if (i + 1 < line.Length && line[i + 1] == '"') { sb.Append('"'); i++; }
                    else inQuotes = false;
                }
                else sb.Append(c);
            }
            else
            {
                if (c == '"') inQuotes = true;
                else if (c == ',') { fields.Add(sb.ToString()); sb.Clear(); }
                else sb.Append(c);
            }
        }
        fields.Add(sb.ToString());
        return fields;
    }

    static void SaveProgress(List<ModEntry> mods)
    {
        try
        {
            var sb = new StringBuilder();
            sb.AppendLine("Index,Name,Url,Status,UpdatedAt");
            foreach (var m in mods)
            {
                sb.AppendLine(string.Join(",",
                    m.Index,
                    CsvEscape(m.Name),
                    CsvEscape(m.Url),
                    CsvEscape(m.Status),
                    CsvEscape(m.UpdatedAt)));
            }
            File.WriteAllText(CsvPath, sb.ToString(), new UTF8Encoding(true));
        }
        catch (Exception ex)
        {
            Console.WriteLine("Could not write progress file: " + ex.Message);
        }
    }

    static string CsvEscape(string? s)
    {
        s ??= "";
        if (s.Contains('"') || s.Contains(',') || s.Contains('\n') || s.Contains('\r'))
            return "\"" + s.Replace("\"", "\"\"") + "\"";
        return s;
    }
}

// One row of the collection CSV
class ModEntry
{
    public int Index;
    public string Name = "";
    public string Url = "";
    public string Status = "pending";
    public string UpdatedAt = "";
}
